import Nav from "@/components/Header/nav";
import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "carocaroocarooo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F1EEE6]">
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}
