import Nav from "@/components/Header/nav";
import { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../global.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "carocaroocarooo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} bg-[#F1EEE6]`}>
        <header className="h-screen fixed top-0 left-0">
          <Nav />
        </header>
        <main className="md:ml-45 font-roboto">{children}</main>
      </body>
    </html>
  );
}
