import Nav from "@/components/Header/nav";
import { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../global.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "carocaroocarooo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoMono.variable}>
      <body className={`bg-[#F1EEE6]`}>
        <header className="md:h-screen md:fixed md:top-0 md:left-0">
          <Nav />
        </header>
        <main className="md:ml-55">
          <div className="mx-10 mt-10 md:mt-19">{children}</div>
        </main>
      </body>
    </html>
  );
}
