import Nav from "@/components/Header/nav";
import { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "../global.css";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "carocaroocarooo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoMono.variable}>
      <body className={`bg-[#F1EEE6]`}>
        <header className="h-screen fixed top-0 left-0">
          <Nav />
        </header>
        <main className="md:ml-45 font-roboto-mono">{children}</main>
      </body>
    </html>
  );
}
